name = "bidxaagui-portfolio"
compatibility_date = "2023-10-30"

[dev]
port = 8788
local_protocol = "http"

[env.production]
name = "bidxaagui-portfolio-prod"
route = "https://bidxaagui.com/*"

[[d1_databases]]
binding = "DB"
database_name = "bidxaagui-db"
database_id = ""
